"""Build the offline nationwide rail catalogue from the checked-in source snapshot."""
import argparse
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REGIONS = [
    ("hokkaido", "❄️ ほっかいどう", [1]),
    ("tohoku", "🍎 とうほく", list(range(2, 8))),
    ("kanto", "🗼 かんとう", list(range(8, 15))),
    ("chubu", "🗻 ちゅうぶ", list(range(15, 24))),
    ("kinki", "🏯 きんき", list(range(24, 31))),
    ("chugoku", "🍁 ちゅうごく", list(range(31, 36))),
    ("shikoku", "🍊 しこく", list(range(36, 40))),
    ("kyushu", "🌋 きゅうしゅう", list(range(40, 47))),
    ("okinawa", "🌺 おきなわ", [47]),
]


def distance(a, b):
    lon1, lat1, lon2, lat2 = map(math.radians, [a[2], a[3], b[2], b[3]])
    h = math.sin((lat2-lat1)/2)**2 + math.cos(lat1)*math.cos(lat2)*math.sin((lon2-lon1)/2)**2
    return 6371.0088 * 2 * math.asin(min(1, math.sqrt(h)))


def regions_for(prefectures):
    return [key for key, _, members in REGIONS if set(prefectures) & set(members)]


def style_for(line, config):
    code, name = line['code'], line['name']
    if '新幹線' in name:
        profile, speed, cars, icon = 'shinkansen', 220, 12, '🚄'
    elif 'ケーブル' in name:
        profile, speed, cars, icon = 'cable', 12, 1, '🚞'
    elif any(s in name for s in ['市電', '電軌', '広電', 'とさでん', '都電', '世田谷', 'ライトレール', '富山地鉄市内', '富山都心', '万葉線', '東田本線', '運動公園前']):
        profile, speed, cars, icon = 'tram', 35, 1, '🚋'
    elif any(s in name for s in ['地下鉄', 'OsakaMetro', '東京メトロ', '都営']):
        profile, speed, cars, icon = 'subway', 70, 6, '🚇'
    else:
        profile, speed, cars, icon = 'commuter', 85, 4, '🚆'
    profile = config['profileOverrides'].get(str(code), profile)
    if profile in ['newtransit', 'monorail']:
        speed, cars, icon = 55, 4, '🚝'
    return {'profile': profile, 'speedKmh': speed, 'cars': cars, 'icon': icon,
            'noPantograph': profile in ['newtransit', 'monorail', 'cable'] or code in config['noPantographCodes']}


def build():
    db = json.loads((ROOT/'data/station-database.json').read_text('utf8'))
    config = json.loads((ROOT/'data/rail-route-overrides.json').read_text('utf8'))
    rows, coverage = [], []
    preserve = set(config['preserveKeys']) - set(config['refreshKeys'])
    for line in db['lines']:
        code = str(line['code'])
        if line['closed']:
            coverage.append({'code':line['code'], 'name':line['name'], 'status':'closed'})
            continue
        if code in config['aliases']:
            coverage.append({'code':line['code'], 'name':line['name'], 'status':'alias', 'canonical':config['aliases'][code]})
            continue
        specs = config['paths'].get(code, [{'stations':line['stations']}])
        covered, keys = set(), []
        for index, spec in enumerate(specs):
            ids = [sid for sid in spec['stations'] if not db['stations'][str(sid)][5]]
            assert len(ids) >= 2, (code, ids)
            covered.update(ids)
            stations = [db['stations'][str(sid)] for sid in ids]
            base_key = config['existingKeys'].get(code, 'railLine'+code)
            key = base_key if index == 0 else f'{base_key}Branch{index}'
            keys.append(key)
            km, points = 0, []
            for i, station in enumerate(stations):
                if i:
                    km += max(0.1, distance(stations[i-1], station))
                points.append([station[1], round(km, 1), station[2], station[3]])
            prefs = sorted(set(s[4] for s in stations))
            name = line['name_kana'].removeprefix('じぇいあーる').replace('はなせきせん', 'はなさきせん')
            row = {'key':key, 'sourceCode':line['code'], 'name':name,
                   'title':line['name'], 'color':line.get('color', '#3478c4'),
                   **style_for(line, config), 'regions':regions_for(prefs),
                   'stationNames':[s[0] for s in stations], 'stationCodes':ids, 'p':points}
            if key in preserve:
                row['preserve'] = True
            if spec.get('loop'):
                row['loop'] = True
            rows.append(row)
        expected = {sid for sid in line['stations'] if not db['stations'][str(sid)][5]}
        assert covered == expected, (line['name'], expected-covered, covered-expected)
        coverage.append({'code':line['code'], 'name':line['name'], 'status':'included', 'routes':keys})
    rows.extend(config['supplements'])
    assert len({r['key'] for r in rows}) == len(rows)
    js = '// Generated by tools/build-rail-network.py. Sources and modifications: data/README.md.\n'
    js += '(() => {\n  "use strict";\n  const data = window.TRAIN_GO_ROUTE_DATA;\n  const sources = [\n'
    js += ',\n'.join('    '+json.dumps(r,ensure_ascii=False,separators=(',',':')) for r in rows)
    js += '\n  ];\n'
    js += '  data.railRegions = '+json.dumps([{'key':k,'name':n} for k,n,_ in REGIONS],ensure_ascii=False)+';\n'
    js += (ROOT/'tools/rail-network-runtime.js').read_text('utf8')
    js += '\n})();\n'
    report = {'version':db['version'], 'source':db['source'], 'activeSourceLines':sum(not l['closed'] for l in db['lines']),
              'includedSourceLines':sum(r['status']=='included' for r in coverage),
              'aliasSourceLines':sum(r['status']=='alias' for r in coverage),
              'supplementalRoutes':len(config['supplements']), 'routes':len(rows), 'lines':coverage}
    return {'all-rail-route-data.js':js, 'data/rail-coverage.json':json.dumps(report,ensure_ascii=False,indent=2)+'\n'}


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check',action='store_true',help='Fail if generated files differ; does not write files.')
    args = parser.parse_args()
    for name, text in build().items():
        path = ROOT/name
        if args.check:
            assert path.read_text('utf8') == text, f'{name} is stale; run tools/build-rail-network.py'
        else:
            path.write_text(text,'utf8')
        print(('checked' if args.check else 'wrote'),name)
