"""Build the domestic passenger airport-pair catalogue from the reviewed source snapshot."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
source = json.loads((ROOT/'data/air-network.json').read_text('utf8'))
payload = json.dumps([source['airports'], source['pairs']], ensure_ascii=False, separators=(',', ':'))
runtime = (ROOT/'tools/air-network-runtime.js').read_text('utf8')
(ROOT/'all-air-route-data.js').write_text(
    '// Generated by tools/build-air-network.py. Sources: data/transport-network.md\n'
    + '(() => {\n  const [airports, pairs] = ' + payload + ';\n' + runtime + '\n})();\n',
    encoding='utf8', newline='\n')
print(f'{len(source["airports"])} airports / {len(source["pairs"])} domestic passenger pairs')
