"""Build long through-service courses from the pinned station database."""
import json
import runpy
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
helpers=runpy.run_path(str(ROOT/'tools/build-rail-network.py'))
distance=helpers['distance']
regions_for=helpers['regions_for']
db=json.loads((ROOT/'data/station-database.json').read_text('utf8'))
config=json.loads((ROOT/'data/rail-route-overrides.json').read_text('utf8'))
lines={l['code']:l for l in db['lines']}
JR='https://www.jreast.co.jp/estation/facility_search.aspx?searchCategoryCd=1'
TOBU='https://www.tobu.co.jp/corporation/rail/route/'
TOKYU='https://transfer.navitime.biz/tokyu/pc/diagram/TrainDiagram?rrCd=00001016&stCd=00009364&updown=0'

def leg(code,start,end,path_index=0):
    return [code,start,end,path_index]

tokyo_ueno=leg(11343,'とうきょう','うえの')
toyo_south=[leg(28010,'こたけむかいはら','しぶや'),leg(26001,'しぶや','よこはま'),leg(99310,'よこはま','もとまちちゅうかがい')]
denentoshi=[leg(26003,'ちゅうおうりんかん','しぶや'),leg(28008,'しぶや','おしあげ'),leg(21002,'おしあげ','ひきふね',1)]
services=[
 ('throughNumazuUtsunomiya','上野東京ライン・沼津〜宇都宮','うえのとうきょうライン','uenoTokyo',JR,
  [leg(11501,'ぬまづ','あたみ'),leg(11301,'あたみ','とうきょう'),tokyo_ueno,leg(11319,'うえの','うつのみや')]),
 ('throughAtamiTakasaki','上野東京ライン・熱海〜高崎','うえのとうきょうライン','uenoTokyo',JR,
  [leg(11301,'あたみ','とうきょう'),tokyo_ueno,leg(11323,'うえの','たかさき')]),
 ('throughZushiUtsunomiya','湘南新宿ライン・逗子〜宇都宮','しょうなんしんじゅくライン','shonanShinjuku',JR,
  [leg(11308,'ずし','おおふな'),leg(11333,'おおふな','おおみや'),leg(11319,'おおみや','うつのみや')]),
 ('throughOdawaraTakasaki','湘南新宿ライン・小田原〜高崎','しょうなんしんじゅくライン','shonanShinjuku',JR,
  [leg(11301,'おだわら','おおふな'),leg(11333,'おおふな','おおみや'),leg(11323,'おおみや','たかさき')]),
 ('throughChuorinkanKuki','田園都市・半蔵門・東武線・中央林間〜久喜','でんえんとし・はんぞうもん・とうぶせん','tokyuDenentoshi',TOBU,
  denentoshi+[leg(21002,'ひきふね','くき')]),
 ('throughChuorinkanMinamikurihashi','田園都市・半蔵門・東武線・中央林間〜南栗橋','でんえんとし・はんぞうもん・とうぶせん','tokyuDenentoshi',TOBU,
  denentoshi+[leg(21002,'ひきふね','とうぶどうぶつこうえん'),leg(21003,'とうぶどうぶつこうえん','みなみくりはし')]),
 ('throughOgawamachiYokohama','東武・副都心・東横・みなとみらい線・小川町〜元町・中華街','とうぶ・ふくとしん・とうよこせん','toyoko',TOKYU,
  [leg(21001,'おがわまち','わこうし'),leg(28010,'わこうし','こたけむかいはら')]+toyo_south),
 ('throughHannoYokohama','西武・副都心・東横・みなとみらい線・飯能〜元町・中華街','せいぶ・ふくとしん・とうよこせん','toyoko',TOKYU,
  [leg(22001,'はんのう','ねりま'),leg(22003,'ねりま','こたけむかいはら')]+toyo_south),
 ('throughChichibuYokohama','西武・副都心・東横・みなとみらい線・西武秩父〜元町・中華街','せいぶ・ふくとしん・とうよこせん','toyoko',TOKYU,
  [leg(22002,'せいぶちちぶ','あがの'),leg(22001,'あがの','ねりま'),leg(22003,'ねりま','こたけむかいはら')]+toyo_south),
]
rows=[]
for key,title,name,train,source,legs in services:
    stations=[]; pairs=[]; members=set();codes=[]
    for code,start,end,index in legs:
        line=lines[code]
        ids=config['paths'].get(str(code),[{'stations':line['stations']}])[index]['stations']
        segment=[db['stations'][str(s)] for s in ids if not db['stations'][str(s)][5]]
        names=[s[1].replace('・','') for s in segment]
        a,b=names.index(start),names.index(end)
        segment=segment[a:b+1] if a<=b else list(reversed(segment[b:a+1]))
        assert len(segment)>1,(key,code)
        if stations:
            assert stations[-1][1]==segment[0][1] and distance(stations[-1],segment[0])<1,(key,code,'disconnected')
        if 28000<code<29000:
            pairs.extend([[a[1],b[1]] for a,b in zip(segment,segment[1:])])
        stations.extend(segment[1:] if stations else segment)
        members.add(config['existingKeys'].get(str(code),'railLine'+str(code)))
        codes.append(code)
    points=[]; km=0
    for i,s in enumerate(stations):
        if i: km+=distance(stations[i-1],s)
        points.append([s[1],round(km,1),s[2],s[3]])
    if 21002 in codes: members.add('tobuSkytree')
    members.add(train)
    rows.append({'key':key,'title':title,'name':name,'trainKey':train,'source':source,'members':sorted(members),'sourceCodes':codes,
                 'regions':regions_for([s[4] for s in stations]),'stationNames':[s[0] for s in stations],'p':points,'tunnelPairs':pairs})
header='// Generated by tools/build-through-routes.py. Operational references: data/through-services.md.\n'
text=header+'(() => {\n  const data = window.TRAIN_GO_ROUTE_DATA;\n  const sources = '+json.dumps(rows,ensure_ascii=False,separators=(',',':'))+';\n'
text+='''  data.throughRoutes = sources;
  for (const item of sources) {
    const color = data.maps[item.trainKey]?.color || "#e87523";
    const stations = item.p.slice(1).map(([name,km]) => ({name,km}));
    stations.push({name:item.p[0][0],km:0});
    data.routes[item.key] = {name:item.name,start:item.p[0][0],startKm:0,stations,
      supportsExpress:false,allowCrossings:true,expressStops:new Set(),cityStations:new Set(),tunnelPairs:item.tunnelPairs};
    data.maps[item.key] = {name:item.name,color,points:item.p};
    data.metadata.push({key:item.key,name:item.name,color,trainKey:item.trainKey,kind:"rail",icon:"🔗",cars:10,speedKmh:95});
    data.routeCatalog[item.key] = {title:item.title,regions:item.regions,kind:"rail",through:true,
      search:[item.title,item.name,...item.stationNames,...item.p.map(p=>p[0])].join(" "),
      endpoints:`${item.p[0][0]} 〜 ${item.p.at(-1)[0]}`};
    data.allRailRouteKeys.push(item.key);
    data.stationLabelsByRoute[item.key] = Object.fromEntries(item.p.map((p,i)=>[p[0],item.stationNames[i].replace(/[（(].*?[)）]/g,"")]));
  }
})();
'''
(ROOT/'through-route-data.js').write_text(text,encoding='utf8',newline='\n')
print([(r['key'],len(r['p']),r['p'][-1][1]) for r in rows])
