// Generated by tools/build-roads.py. Geometry: OpenStreetMap contributors (ODbL).
(() => {
  'use strict';
  const data=window.TRAIN_GO_ROUTE_DATA;
  const vehicles=[
    ['carCompact','コンパクトカー','こんぱくとかー','#ee684f','compact'],
    ['carKei','軽自動車','けいじどうしゃ','#f0c94e','kei'],
    ['carSedan','セダン','せだん','#e6edf4','sedan'],
    ['carSuv','SUV','えすゆーぶい','#56885d','suv'],
    ['carMinivan','ミニバン','みにばん','#669ad1','minivan'],
    ['carBus','バス','ばす','#f3ede0','bus'],
    ['carTruck','トラック','とらっく','#5d9ccb','truck'],
    ['carFireEngine','消防車','しょうぼうしゃ','#e64840','fireEngine',true],
    ['carPolice','パトカー','ぱとかー','#f4f6f7','police',true],
    ['carExcavator','ショベルカー','しょべるかー','#efbf37','excavator',true],
    ['carDumpTruck','ダンプカー','だんぷかー','#edb539','dumpTruck',true],
    ['carAmbulance','救急車','きゅうきゅうしゃ','#f4f6f7','ambulance',true],
    ['carGarbageTruck','ごみ収集車','ごみしゅうしゅうしゃ','#65a875','garbageTruck',true],
    ['carMixerTruck','ミキサー車','みきさーしゃ','#62a5ce','mixerTruck',true],
    ['carCraneTruck','クレーン車','くれーんしゃ','#f2c344','craneTruck',true],
    ['carLadder','はしご車','はしごしゃ','#e64840','ladder',true],
    ['carAerial','高所作業車','こうしょさぎょうしゃ','#e7bd3f','aerial',true],
    ['carSnowplow','除雪車','じょせつしゃ','#ed963e','snowplow',true],
    ['carTow','レッカー車','れっかーしゃ','#508fc5','tow',true],
    ['carTanker','タンクローリー','たんくろーりー','#d6dce0','tanker',true],
    ['carSweeper','道路清掃車','どうろせいそうしゃ','#69a7bf','sweeper',true],
    ['carRoller','ロードローラー','ろーどろーらー','#e9b533','roller',true],
    ['carBulldozer','ブルドーザー','ぶるどーざー','#e7bd3f','bulldozer',true],
    ['carStairs','タラップ車','たらっぷしゃ','#edf3f5','stairs',true],
    ['carAirportTug','トーイングトラクター','とーいんぐとらくたー','#edc43d','airportTug',true],
    ['carHighLoader','ハイリフトローダー','はいりふとろーだー','#e9edf1','highLoader',true],
    ['carBeltLoader','ベルトローダー','べるとろーだー','#eff2e5','beltLoader',true],
    ['carAirportFuel','航空機給油車','こうくうききゅうゆしゃ','#c3dce8','airportFuel',true],
  ];
  for(const [key,title,name,body,shape,workVehicle=false] of vehicles)data.trains[key]={name,title,kind:'car',shape,body,workVehicle,stripe:'#405b71',edge:'#334858',face:'#b5def0',callName:name};
  const roads=/* ROAD_RECORDS */;
  const keys=[];
  for(const [id,category,title,name,courses,,refs] of roads)courses.forEach((course,index)=>{
    const [startTitle,start,endTitle,end,delta]=course;
    const key=`road${id}_${index}`,points=[];let lon=0,lat=0,km=0;
    for(let i=0;i<delta.length;i+=2){
      lon+=delta[i];lat+=delta[i+1];
      const x=lon/10000,y=lat/10000,previous=points.at(-1);
      if(previous)km+=Math.hypot((x-previous[2])*Math.cos((y+previous[3])*Math.PI/360),y-previous[3])*111.32;
      points.push(['',km,x,y]);
    }
    points[0][0]=start;points.at(-1)[0]=end;
    const suffix=courses.length>1?` (${index+1})`:'';
    const color=category==='expressway'?'#47875a':category==='national'?'#bf9049':'#a69b77';
    data.routes[key]={name:name+suffix,kind:'road',start,startKm:0,supportsExpress:false,allowCrossings:false,
      stations:[{name:end,km},{name:start,km:0}],expressStops:new Set(),cityStations:new Set()};
    data.maps[key]={name:name+suffix,kind:'road',color,points};
    data.metadata.push({key,name:name+suffix,color,icon:'🚗',trainKey:'carCompact',kind:'road',speedKmh:category==='expressway'?100:60});
    data.routeCatalog[key]={title:title+suffix,kind:'road',regions:[],sourceCode:`road:${id}`,search:`${title} ${name} ${startTitle} ${endTitle} ${(refs||[]).join(' ')}`};
    data.stationLabelsByRoute[key]={[start]:startTitle,[end]:endTitle};keys.push(key);
  });
  data.roadNetwork={keys,vehicleKeys:vehicles.map(v=>v[0]),roadCount:roads.length};
})();
