(() => {
  "use strict";
  const room=document.querySelector("#room"),messageText=document.querySelector("#messageText"),inventoryItems=document.querySelector("#inventoryItems"),introOverlay=document.querySelector("#introOverlay"),modalOverlay=document.querySelector("#modalOverlay"),endingOverlay=document.querySelector("#endingOverlay"),modalTitle=document.querySelector("#modalTitle"),modalEyebrow=document.querySelector("#modalEyebrow"),modalContent=document.querySelector("#modalContent");
  const freshState=()=>({lightOn:true,readNote:false,sawWindowClue:false,sawCalendar:false,boxOpen:false,hasKey:false,drawerOpen:false,clockHour:22,clockMinute:0,clockSolved:false,doorUnlocked:false});
  let state=freshState();
  const setMessage=text=>{messageText.textContent=text};
  function showModal(title,html,eyebrow="FOUND"){modalTitle.textContent=title;modalEyebrow.textContent=eyebrow;modalContent.innerHTML=html;modalOverlay.classList.add("visible");setTimeout(()=>modalOverlay.querySelector("input, button")?.focus(),30)}
  const closeModal=()=>modalOverlay.classList.remove("visible");
  function updateView(){room.classList.toggle("light-on",state.lightOn);document.querySelector(".box").classList.toggle("open",state.boxOpen);document.querySelector(".drawer").classList.toggle("open",state.drawerOpen);document.querySelector(".hour-hand").style.transform=`rotate(${(state.clockHour%12)*30+state.clockMinute*.5}deg)`;document.querySelector(".minute-hand").style.transform=`rotate(${state.clockMinute*6}deg)`;inventoryItems.innerHTML=state.hasKey&&!state.drawerOpen?'<span class="item">小さな鍵</span>':'<span class="empty">まだ何もない</span>'}
  function readNote(){state.readNote=true;setMessage("紙には、誰かの手書きの文章が残っている。");showModal("机の上の紙",'<div class="paper"><p>ここに残った私へ。</p><p>夜の窓は、昼には見えないことを覚えている。</p><p>三つの天気を、カレンダーで順にたどれ。</p><p>時計を正しい夜に戻せば、扉はきっと思い出す。</p></div>',"A NOTE FOR YOU")}
  function inspectWindow(){if(state.lightOn){setMessage("室内の光が窓に反射して、外はよく見えない。");showModal("古い窓","<p>外には何も見えない。明かりを消せば、ガラスの向こうが見えるだろうか。</p>");return}state.sawWindowClue=true;setMessage("曇ったガラスに『雨　晴　雪』の文字が浮かんでいる。");showModal("暗闇に残った文字",'<p>消した明かりの向こうで、三つの文字だけが淡く光っている。</p><div class="paper big-clue">雨　晴　雪</div>',"ON THE GLASS")}
  function inspectCalendar(){state.sawCalendar=true;setMessage("四月のカレンダー。1日、3日、18日に、それぞれ違う印がある。");showModal("四月のカレンダー",'<div class="paper"><p><strong>1日</strong>には雪の結晶。</p><p><strong>3日</strong>には雨粒。</p><p><strong>18日</strong>には太陽。18日だけ、赤い線で二重に囲まれている。</p></div>',"APRIL")}
  function inspectBox(){if(state.boxOpen){setMessage("木箱は空になっている。");return}showModal("三桁錠の木箱",'<p>三桁の数字を入力する錠がついている。</p><form class="code-form" id="boxCodeForm"><input id="boxCode" inputmode="numeric" autocomplete="off" maxlength="3" pattern="[0-9]*" aria-label="木箱の暗証番号" placeholder="000"><button type="submit">開ける</button></form>',"LOCKED BOX");document.querySelector("#boxCodeForm").addEventListener("submit",event=>{event.preventDefault();if(document.querySelector("#boxCode").value==="318"){state.boxOpen=true;state.hasKey=true;updateView();setMessage("箱が開いた。中から小さな鍵を手に入れた。");showModal("小さな鍵",'<p>古びた真鍮の鍵だ。机の引き出しに合いそうだ。</p><span class="item">小さな鍵</span>',"ITEM FOUND")}else{setMessage("錠は動かない。三つの天気とカレンダーが関係していそうだ。");document.querySelector("#boxCode").select()}})}
  function inspectDrawer(){if(!state.hasKey&&!state.drawerOpen){setMessage("引き出しには鍵がかかっている。");showModal("机の引き出し","<p>小さな鍵穴がある。手では開きそうにない。</p>","LOCKED");return}state.drawerOpen=true;updateView();setMessage("引き出しから、一枚の古い写真が出てきた。");showModal("引き出しの写真",'<div class="photo"><div class="photo-scene">23:40</div><small>最後の夜、この部屋で。</small></div><p>写真の時計は、23時40分で止まっている。</p>',"AN OLD PHOTO")}
  function inspectClock(){showModal("止まった時計",`<p>針は手で動かせそうだ。</p><div class="clock-display" id="clockDisplay">${state.clockHour}:${String(state.clockMinute).padStart(2,"0")}</div><div class="clock-controls"><button type="button" data-clock="hour-minus">時 −</button><button type="button" data-clock="hour-plus">時 ＋</button><button type="button" data-clock="minute-minus">分 −</button><button type="button" data-clock="minute-plus">分 ＋</button><button type="button" data-clock="set">この時刻に合わせる</button></div>`,"STOPPED CLOCK");modalContent.querySelectorAll("[data-clock]").forEach(button=>button.addEventListener("click",()=>adjustClock(button.dataset.clock)))}
  function adjustClock(action){if(action==="hour-minus")state.clockHour=state.clockHour===0?23:state.clockHour-1;if(action==="hour-plus")state.clockHour=state.clockHour===23?0:state.clockHour+1;if(action==="minute-minus")state.clockMinute=state.clockMinute===0?50:state.clockMinute-10;if(action==="minute-plus")state.clockMinute=state.clockMinute===50?0:state.clockMinute+10;updateView();document.querySelector("#clockDisplay").textContent=`${state.clockHour}:${String(state.clockMinute).padStart(2,"0")}`;if(action!=="set")return;if(state.clockHour===23&&state.clockMinute===40){state.clockSolved=true;setMessage("時計の奥で何かが外れる音がした。裏から紙片が落ちた。");showModal("時計の裏の紙片",'<div class="paper"><p>私たちがここを出た日。</p><p class="date-clue"><strong>04 18</strong></p><p>扉は、まだ覚えている。</p></div>',"THE LAST DATE")}else setMessage("何も起きない。この部屋にとって大切な時刻があるはずだ。")}
  function inspectDoor(){if(state.doorUnlocked){showFinalLetter();return}showModal("出口の扉",'<p>取っ手は動かない。脇のテンキーに四桁の数字を入力できる。</p><form class="code-form" id="doorCodeForm"><input id="doorCode" inputmode="numeric" autocomplete="off" maxlength="4" pattern="[0-9]*" aria-label="扉の暗証番号" placeholder="0000"><button type="submit">解錠する</button></form>',"THE EXIT");document.querySelector("#doorCodeForm").addEventListener("submit",event=>{event.preventDefault();if(document.querySelector("#doorCode").value==="0418"&&state.clockSolved){state.doorUnlocked=true;closeModal();setMessage("扉の鍵が開いた。向こうから、朝の光が差し込んでくる。");setTimeout(showFinalLetter,450)}else{setMessage(state.clockSolved?"扉は開かない。最後に見つけた日付を四桁で。":"まず、この部屋の記憶をたどる必要がありそうだ。");document.querySelector("#doorCode").select()}})}
  function showFinalLetter(){endingOverlay.classList.add("visible");document.querySelector("#endingContent").innerHTML='<div class="paper"><p>ここまで来た、部屋に残った私へ。</p><p>あなたは私ではない。ここで過ごした時間から生まれた、ひとつの記憶です。</p><p>私は昨日、この町を出ました。だから「昨日までの私」は、もうどこにもいません。</p><p>部屋は明日なくなる。でも最後に、あなたにも朝を見せてあげたかった。</p></div><p>扉の先には、白い朝がある。<br>この部屋に残ることも、外へ出ることもできる。</p><div class="ending-choice"><button type="button" data-ending="stay">部屋に残る</button><button type="button" data-ending="leave">朝へ出る</button></div>';document.querySelectorAll("[data-ending]").forEach(button=>button.addEventListener("click",()=>showEnding(button.dataset.ending)))}
  function showEnding(choice){const stay=choice==="stay";document.querySelector("#endingTitle").textContent=stay?"最後の一秒まで":"記憶は、扉の外へ";document.querySelector("#endingContent").innerHTML=`<p>${stay?"あなたは、空っぽになった部屋に座った。やがて朝日が窓から差し込み、すべてを金色に染めていく。消えることは、なかったことになることではない。最後の一秒まで、ここは確かに誰かの居場所だった。":"あなたが扉を越えた瞬間、背後で部屋の気配が静かにほどけた。持ち出せるものは何もなかった。それでも、朝の空気の中に、カーテンの色も、古い時計の音も、確かに残っている気がした。"}</p><p class="final-mark">ESCAPE COMPLETE — END ${stay?"B":"A"}</p><button class="primary-button" id="playAgainButton" type="button">もう一度、目を開ける</button>`;document.querySelector("#playAgainButton").addEventListener("click",resetGame)}
  function showHint(){let hint="まずは机の上の紙を読んでみよう。";if(state.readNote&&state.lightOn)hint="窓は室内の光を反射している。壁のスイッチを押してみよう。";else if(state.readNote&&!state.sawWindowClue)hint="暗くなった窓を、もう一度調べてみよう。";else if(state.sawWindowClue&&!state.sawCalendar)hint="『雨・晴・雪』それぞれの日を、四月のカレンダーで探そう。";else if(!state.boxOpen)hint="雨は3日、晴は18日、雪は1日。窓に出た順に数字を並べると三桁になる。";else if(!state.drawerOpen)hint="手に入れた小さな鍵は、机の引き出しに使えそうだ。";else if(!state.clockSolved)hint="写真に写った時計は23:40。壁の時計を同じ時刻に合わせよう。";else if(!state.doorUnlocked)hint="時計の裏の『04 18』を、扉のテンキーへ四桁で入力しよう。";else hint="開いた扉をタップして、最後の記憶を読もう。";showModal("いま分かること",`<p>${hint}</p>`,"HINT")}
  function toggleLight(){state.lightOn=!state.lightOn;updateView();setMessage(state.lightOn?"照明をつけた。古い電球が小さく唸っている。":"照明を消した。窓のガラスに、何かが浮かんでいる。")}
  function resetGame(){state=freshState();closeModal();endingOverlay.classList.remove("visible");introOverlay.classList.add("visible");document.querySelector("#endingTitle").textContent="最後の手紙";setMessage("机の上に、古びた紙が置かれている。");updateView()}
  const actions={note:readNote,window:inspectWindow,calendar:inspectCalendar,box:inspectBox,drawer:inspectDrawer,clock:inspectClock,door:inspectDoor,switch:toggleLight,picture:()=>showModal("色褪せた額縁",'<p>部屋の古い写真に、短い言葉が添えられている。</p><div class="paper">この部屋を忘れない。</div>')};
  document.querySelectorAll("[data-object]").forEach(object=>object.addEventListener("click",()=>actions[object.dataset.object]()));document.querySelector("#startButton").addEventListener("click",()=>introOverlay.classList.remove("visible"));document.querySelector("#modalClose").addEventListener("click",closeModal);document.querySelector("#hintButton").addEventListener("click",showHint);document.querySelector("#resetButton").addEventListener("click",resetGame);modalOverlay.addEventListener("click",event=>{if(event.target===modalOverlay)closeModal()});document.addEventListener("keydown",event=>{if(event.key==="Escape"&&modalOverlay.classList.contains("visible"))closeModal()});updateView();
})();
